name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rust-armv6:$(date +%s)

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: endbasic-armv6
        path: ${{github.workspace}}/work
